# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created: Tue Apr 26 10:27:35 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Mosaic(object):
    def setupUi(self, Mosaic):
        Mosaic.setObjectName(_fromUtf8("Mosaic"))
        Mosaic.resize(813, 556)
        Mosaic.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.startButton = QtGui.QPushButton(Mosaic)
        self.startButton.setGeometry(QtCore.QRect(690, 510, 98, 27))
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.editDirPath = QtGui.QLineEdit(Mosaic)
        self.editDirPath.setGeometry(QtCore.QRect(30, 60, 421, 31))
        self.editDirPath.setReadOnly(True)
        self.editDirPath.setObjectName(_fromUtf8("editDirPath"))
        self.dirPickLabel = QtGui.QLabel(Mosaic)
        self.dirPickLabel.setGeometry(QtCore.QRect(30, 40, 131, 16))
        self.dirPickLabel.setObjectName(_fromUtf8("dirPickLabel"))
        self.openButton = QtGui.QPushButton(Mosaic)
        self.openButton.setGeometry(QtCore.QRect(470, 60, 98, 27))
        self.openButton.setObjectName(_fromUtf8("openButton"))
        self.widthSpinBox = QtGui.QSpinBox(Mosaic)
        self.widthSpinBox.setGeometry(QtCore.QRect(20, 180, 60, 27))
        self.widthSpinBox.setMaximum(10000)
        self.widthSpinBox.setObjectName(_fromUtf8("widthSpinBox"))
        self.heightSpinBox = QtGui.QSpinBox(Mosaic)
        self.heightSpinBox.setGeometry(QtCore.QRect(160, 180, 60, 27))
        self.heightSpinBox.setMaximum(10000)
        self.heightSpinBox.setObjectName(_fromUtf8("heightSpinBox"))
        self.widthLabel = QtGui.QLabel(Mosaic)
        self.widthLabel.setGeometry(QtCore.QRect(20, 160, 66, 17))
        self.widthLabel.setObjectName(_fromUtf8("widthLabel"))
        self.heightLabel = QtGui.QLabel(Mosaic)
        self.heightLabel.setGeometry(QtCore.QRect(160, 160, 66, 17))
        self.heightLabel.setObjectName(_fromUtf8("heightLabel"))
        self.line = QtGui.QFrame(Mosaic)
        self.line.setGeometry(QtCore.QRect(0, 110, 811, 21))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label = QtGui.QLabel(Mosaic)
        self.label.setGeometry(QtCore.QRect(20, 130, 111, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.line_2 = QtGui.QFrame(Mosaic)
        self.line_2.setGeometry(QtCore.QRect(0, 230, 811, 21))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_2 = QtGui.QLabel(Mosaic)
        self.label_2.setGeometry(QtCore.QRect(20, 250, 161, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.maxGenNumberLabel = QtGui.QLabel(Mosaic)
        self.maxGenNumberLabel.setGeometry(QtCore.QRect(20, 290, 201, 17))
        self.maxGenNumberLabel.setObjectName(_fromUtf8("maxGenNumberLabel"))
        self.maxGenNumberSpinBox = QtGui.QSpinBox(Mosaic)
        self.maxGenNumberSpinBox.setGeometry(QtCore.QRect(20, 310, 60, 27))
        self.maxGenNumberSpinBox.setMaximum(10000)
        self.maxGenNumberSpinBox.setObjectName(_fromUtf8("maxGenNumberSpinBox"))
        self.beeNumberSpinBox = QtGui.QSpinBox(Mosaic)
        self.beeNumberSpinBox.setGeometry(QtCore.QRect(320, 310, 60, 27))
        self.beeNumberSpinBox.setMaximum(10000)
        self.beeNumberSpinBox.setObjectName(_fromUtf8("beeNumberSpinBox"))
        self.beeNumberLabel = QtGui.QLabel(Mosaic)
        self.beeNumberLabel.setGeometry(QtCore.QRect(320, 290, 181, 17))
        self.beeNumberLabel.setObjectName(_fromUtf8("beeNumberLabel"))
        self.selectBestedSidesNumberSpinBox = QtGui.QSpinBox(Mosaic)
        self.selectBestedSidesNumberSpinBox.setGeometry(QtCore.QRect(20, 370, 60, 27))
        self.selectBestedSidesNumberSpinBox.setMaximum(10000)
        self.selectBestedSidesNumberSpinBox.setObjectName(_fromUtf8("selectBestedSidesNumberSpinBox"))
        self.selectedBestSidesNumberLabel = QtGui.QLabel(Mosaic)
        self.selectedBestSidesNumberLabel.setGeometry(QtCore.QRect(20, 350, 221, 17))
        self.selectedBestSidesNumberLabel.setObjectName(_fromUtf8("selectedBestSidesNumberLabel"))
        self.eliteSitesNumberSpinBox = QtGui.QSpinBox(Mosaic)
        self.eliteSitesNumberSpinBox.setGeometry(QtCore.QRect(20, 430, 60, 27))
        self.eliteSitesNumberSpinBox.setMaximum(10000)
        self.eliteSitesNumberSpinBox.setObjectName(_fromUtf8("eliteSitesNumberSpinBox"))
        self.eliteSitesNumberLabel = QtGui.QLabel(Mosaic)
        self.eliteSitesNumberLabel.setGeometry(QtCore.QRect(20, 410, 181, 17))
        self.eliteSitesNumberLabel.setObjectName(_fromUtf8("eliteSitesNumberLabel"))
        self.patchSizeSpinBox = QtGui.QSpinBox(Mosaic)
        self.patchSizeSpinBox.setGeometry(QtCore.QRect(580, 300, 60, 27))
        self.patchSizeSpinBox.setMaximum(10000)
        self.patchSizeSpinBox.setObjectName(_fromUtf8("patchSizeSpinBox"))
        self.eliteBeesNumberSpinbox = QtGui.QSpinBox(Mosaic)
        self.eliteBeesNumberSpinbox.setGeometry(QtCore.QRect(320, 370, 60, 27))
        self.eliteBeesNumberSpinbox.setMaximum(10000)
        self.eliteBeesNumberSpinbox.setObjectName(_fromUtf8("eliteBeesNumberSpinbox"))
        self.otherBeesNumberSpinBox = QtGui.QSpinBox(Mosaic)
        self.otherBeesNumberSpinBox.setGeometry(QtCore.QRect(320, 430, 60, 27))
        self.otherBeesNumberSpinBox.setMaximum(10000)
        self.otherBeesNumberSpinBox.setObjectName(_fromUtf8("otherBeesNumberSpinBox"))
        self.patchSizeLabel = QtGui.QLabel(Mosaic)
        self.patchSizeLabel.setGeometry(QtCore.QRect(580, 280, 181, 17))
        self.patchSizeLabel.setObjectName(_fromUtf8("patchSizeLabel"))
        self.eliteBessNumberLabel = QtGui.QLabel(Mosaic)
        self.eliteBessNumberLabel.setGeometry(QtCore.QRect(320, 350, 181, 17))
        self.eliteBessNumberLabel.setObjectName(_fromUtf8("eliteBessNumberLabel"))
        self.otherBeesNumberLabel = QtGui.QLabel(Mosaic)
        self.otherBeesNumberLabel.setGeometry(QtCore.QRect(320, 410, 181, 17))
        self.otherBeesNumberLabel.setObjectName(_fromUtf8("otherBeesNumberLabel"))
        self.patchDecreaseFactorLabel = QtGui.QLabel(Mosaic)
        self.patchDecreaseFactorLabel.setGeometry(QtCore.QRect(580, 350, 181, 17))
        self.patchDecreaseFactorLabel.setObjectName(_fromUtf8("patchDecreaseFactorLabel"))
        self.patchDecreaseFactorSpinBox = QtGui.QDoubleSpinBox(Mosaic)
        self.patchDecreaseFactorSpinBox.setGeometry(QtCore.QRect(580, 370, 62, 27))
        self.patchDecreaseFactorSpinBox.setProperty("value", 0.95)
        self.patchDecreaseFactorSpinBox.setObjectName(_fromUtf8("patchDecreaseFactorSpinBox"))
        self.overlaPenaltySpinBox = QtGui.QSpinBox(Mosaic)
        self.overlaPenaltySpinBox.setGeometry(QtCore.QRect(580, 430, 60, 27))
        self.overlaPenaltySpinBox.setMaximum(10000)
        self.overlaPenaltySpinBox.setObjectName(_fromUtf8("overlaPenaltySpinBox"))
        self.overlapPenaltyLabel = QtGui.QLabel(Mosaic)
        self.overlapPenaltyLabel.setGeometry(QtCore.QRect(580, 410, 181, 17))
        self.overlapPenaltyLabel.setObjectName(_fromUtf8("overlapPenaltyLabel"))

        self.retranslateUi(Mosaic)
        QtCore.QMetaObject.connectSlotsByName(Mosaic)

    def retranslateUi(self, Mosaic):
        Mosaic.setWindowTitle(_translate("Mosaic", "Mosaic", None))
        self.startButton.setText(_translate("Mosaic", "Start", None))
        self.dirPickLabel.setText(_translate("Mosaic", "Choose directory", None))
        self.openButton.setText(_translate("Mosaic", "Open", None))
        self.widthLabel.setText(_translate("Mosaic", "Width", None))
        self.heightLabel.setText(_translate("Mosaic", "Height", None))
        self.label.setText(_translate("Mosaic", "Output image", None))
        self.label_2.setText(_translate("Mosaic", "Bee parameters", None))
        self.maxGenNumberLabel.setText(_translate("Mosaic", "max number of generations", None))
        self.beeNumberLabel.setText(_translate("Mosaic", "number of bees", None))
        self.selectedBestSidesNumberLabel.setText(_translate("Mosaic", "number of selected best sites", None))
        self.eliteSitesNumberLabel.setText(_translate("Mosaic", "number of elite sites", None))
        self.patchSizeLabel.setText(_translate("Mosaic", "patch size", None))
        self.eliteBessNumberLabel.setText(_translate("Mosaic", "number of elite bees ", None))
        self.otherBeesNumberLabel.setText(_translate("Mosaic", "number of other bees", None))
        self.patchDecreaseFactorLabel.setText(_translate("Mosaic", "patch decrease factor", None))
        self.overlapPenaltyLabel.setText(_translate("Mosaic", "overlap penalty", None))

